# Generated by Django 5.2.8 on 2025-11-26 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entry', models.DecimalField(decimal_places=4, max_digits=5)),
                ('close', models.DecimalField(decimal_places=4, max_digits=5)),
                ('profit', models.CharField(max_length=10)),
                ('loss', models.CharField(max_length=10)),
                ('entry_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
