# Generated by Django 5.2.8 on 2025-11-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='close',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='loss',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='lot_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='profit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
