# Generated by Django 5.2.8 on 2025-11-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_journal_close_alter_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
