# Generated by Django 5.2.8 on 2025-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_journal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
