# Generated by Django 5.2.8 on 2025-11-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_journal_close_time_alter_journal_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='close',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
