# Generated by Django 5.2.8 on 2025-11-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_journal_close_alter_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='close_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
