# Generated by Django 5.2.8 on 2025-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_journal_close_time_alter_journal_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry_time',
            field=models.TimeField(),
        ),
    ]
