# Generated by Django 5.2.8 on 2025-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_journal_pair_alter_journal_loss_alter_journal_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='loss',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='profit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
