# Generated by Django 5.2.8 on 2025-11-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_journal_loss_alter_journal_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
