# Generated by Django 5.2.8 on 2025-11-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_journal_loss_alter_journal_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default='0.01', max_digits=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='pair',
            field=models.CharField(choices=[('eur/usd', 'eur/usd'), ('gbp/usd', 'gbp/usd'), ('jpy/usd', 'jpy/usd')], default='eur/usd', max_length=10),
        ),
    ]
