# Generated by Django 5.2.8 on 2025-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_journal_lot_size_alter_journal_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='lot_size',
            field=models.CharField(default='0.01', max_length=10),
        ),
    ]
