# Generated by Django 5.2.8 on 2025-11-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_journal_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
